
workflows:
  android-workflow:
    name: REChain Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.rechain.nodeapp" # Adjusted package name for REChain
        GOOGLE_PLAY_TRACK: "beta" # Assuming this project is in beta phase
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build AAB with Flutter
        script: |
          BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
          flutter build appbundle --release             --build-name=rechain-node-app             --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dmitry.justdev@gmail.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  ios-workflow:
    name: REChain iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rechain.nodeapp # Adjusted bundle identifier
      vars:
        APP_ID: 1234567890 # Replace with correct App Store ID
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/ios/local.properties"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build IPA with Flutter
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - dmitry.justdev@gmail.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true

  web-workflow:
    name: REChain Web Workflow
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build web app
        script: |
          flutter build web --release
          cd build/web
          7z a -r ../web.zip ./*
    artifacts:
      - build/web.zip
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - dmitry.justdev@gmail.com
