name: Bug Report
description: Report a bug or issue with REChain
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the issue here.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you experiencing the issue on?
      options:
        - Android
        - iOS
        - Web
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: REChain version (e.g., 4.1.8+1152)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide any relevant logs or error messages.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
