# Sample OAuth2 config for SSO
client_id: your-client-id
client_secret: your-client-secret
auth_url: https://provider.example.com/oauth/authorize
token_url: https://provider.example.com/oauth/token
redirect_uri: http://localhost:8090/oauth/callback
scope: openid email profile 