name: rechainonline
title: REChain
base: core20
version: 4.1.7
license: AGPL-3.0
summary: The inclusion of polls enhances decision-making processes.
description: |
  REChain is a comprehensive platform that unifies Matrix protocol, blockchain, IPFS, AI, and external services into a seamless, extensible, and developer-friendly ecosystem. It empowers users and developers to build, scale, and secure decentralized apps, bots, and integrations for the future of the internet.


  ## Features

  - Matrix Protocol: Multi-client, multi-server, bridges, bots, federation, and advanced Matrix integrations
  - Blockchain: TON, Ethereum, Bitget, Web3, smart contracts, token/NFT support, on-chain identity
  - IPFS: Multi-provider decentralized storage, file manager, encryption, quotas, analytics, REST/gRPC API
  - AI & Analytics: GPT, moderation, translation, code analysis, monitoring, dashboards
  - Serverless & API: REST, GraphQL, gRPC, WebSocket, serverless hooks, monitoring
  - Security: Encryption, quotas, advanced logging, best practices
  - Modern UI/UX: Flutter-based, responsive, accessible, beautiful dashboards and tools
  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation including all matrix features
  - Discover and join public groups
  - Dark mode
  - Hides complexity of Matrix IDs behind simple QR codes
  - Custom emotes and stickers
  - Video calls via sharing links to Jitsi
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other Matrix apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## REChain.Online comes with a dream!

  Imagine a world where everyone can choose the messenger they like and is still able to chat with all of their friends.

  A world where there are no companies spying on you when you send selfies to friends and lovers.

  And a world where apps are made for awesomeness and not for profit. ♥

  Join the community: https://matrix.to/#/#chatting:matrix.katya.wtf
  Website: http://online.rechain.network
  Microblog: https://instagram.com/rechain_inc

grade: stable
confinement: strict

# platforms:
#   amd64:
#     build-on: amd64
#   arm64:
#     build-on: arm64

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.32.5
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  rechainonline:
    after: [flutter-git]
    plugin: nil
    source: .
    override-build: |
      # Workaround for Flutter build error:
      rm -rf build

      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libssl-dev
      - curl
      - libpciaccess-dev
    build-snaps:
      - rustup
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - libpciaccess0

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: com.rechain.online

apps:
  rechainonline:
    command: bin/rechainonline
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - network-manager-observe
      - opengl
      - removable-media
      - browser-support
      - password-manager-service
    slots:
      - dbus-svc
    # Workaround for:
    # https://github.com/flutter-webrtc/flutter-webrtc/issues/1212#issuecomment-1611899344
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"
