name: rechainonline
title: REChain
base: core24
version: git
license: AGPL-3.0
summary: REChain ®️🪐✨ Platform encourages collaborative communication through features
description: |
  REChain ®️ 🪐 ✨ is an primarily designed as a security and privacy analysis analogue fully focused on the use of platform moments and messages for communication, built on a source code library, including those developed by us, for those who respect freedom and privacy, as well as the safety and security of personal data. 🌤 Our task was to make a tool pleasant and enjoyable to use, with which each of you can communicate, expand content, create workspaces, organize a workflow. 🌈 We strive to show all the world's giants that it is possible to create cool products that are of great importance for society, for people to interact with each other, without selling advertising, personal data of users, their rights and freedoms! 🦄 It's written in Flutter. Our mission is to create an easy to use instant messenger which is open source and accessible for everyone. Donate US! ⌛ For tea, coffee! For the future of decentralized and distributed internet. We do cool and, in my opinion, useful things for the safety and security of users' personal data. And on a completely non-commercial basis! 😎 Join the community: https://matrix.to/#/#chatting:matrix.katya.wtf Website: https://online.rechain.network


  ## Features

  - Send all kinds of messages, images and files
  - Voice messages
  - Location sharing
  - Push notifications
  - Unlimited private and public group chats
  - Public channels with thousands of participants
  - Feature rich group moderation including all REChain features
  - Discover and join public groups
  - Dark mode
  - Hides complexity of REChain IDs behind simple QR codes
  - Custom emotes and stickers
  - Video calls via sharing links to Jitsi
  - Spaces
  - Compatible with Element, Nheko, NeoChat and all other REChain apps
  - End to end encryption
  - Emoji verification & cross signing
  - And much more...


  ## REChain comes with a dream

  Imagine a world where everyone can choose the messenger they like and is still able to chat with all of their friends.

  A world where there are no companies spying on you when you send selfies to friends and lovers.

  Join the community: https://matrix.to/#/#chatting:matrix.katya.wtf
  Website: http://online.rechain.network
  Microblog: https://instagram.com/rechain_inc

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: amd64
  arm64:
    build-on: arm64

parts:
  rechainonline:
    plugin: flutter
    source: .
    override-build: |
      # Workaround for Flutter build error:
      rm -rf build
      craftctl default
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
      - libssl-dev
      - curl
      - libpciaccess-dev
      - cargo
      - rustc
    stage-packages:
      - libsecret-1-0
      - libjsoncpp25
      - libpciaccess0

slots:
  dbus-svc:
    interface: dbus
    bus: session
    name: com.rechain.online

apps:
  rechainonline:
    command: rechainonline
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - home
      - network
      - network-manager
      - network-manager-observe
      - opengl
      - removable-media
      - browser-support
      - password-manager-service
    slots:
      - dbus-svc
    environment:
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET"