name: Telegram Super TMA CI

on:
  push:
    paths:
      - 'bridges/telegram_super_tma/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'bridges/telegram_super_tma/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bridges/telegram_super_tma/requirements.txt
          pip install pytest pyyaml
      - name: Run tests
        run: |
          pytest bridges/telegram_super_tma/test_bot.py 