name: Docker Build and K8s Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'bridges/telegram_super_tma/**'
      - '.github/workflows/docker-k8s.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./bridges/telegram_super_tma
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/supertma:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f bridges/telegram_super_tma/k8s-deployment.yaml 