name: E2E RBAC UI Test

on:
  push:
    paths:
      - 'bridges/telegram_super_tma/rbac_ui.py'
      - 'bridges/telegram_super_tma/test_e2e_rbac.py'
      - '.github/workflows/e2e-rbac.yml'

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Selenium and Chrome
        run: |
          pip install selenium aiohttp aiohttp-session
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Start RBAC UI
        run: |
          nohup python bridges/telegram_super_tma/rbac_ui.py &
          sleep 5
      - name: Run E2E test
        run: |
          python bridges/telegram_super_tma/test_e2e_rbac.py 