name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
    - run: flutter pub get
    - run: flutter build apk --release
    - run: flutter build appbundle --release
    - run: flutter build ios --release --no-codesign
    - run: flutter build web --release
    - run: flutter build linux --release
    - run: flutter build windows --release
    - uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
    - uses: actions/upload-artifact@v3
      with:
        name: android-aab
        path: build/app/outputs/bundle/release/app-release.aab
    - uses: actions/upload-artifact@v3
      with:
        name: ios
        path: build/ios/iphoneos/Runner.app
    - uses: actions/upload-artifact@v3
      with:
        name: web
        path: build/web
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: build/linux/x64/release/bundle
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: build/windows/x64/runner/Release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: android-apk
    - uses: actions/download-artifact@v3
      with:
        name: android-aab
    - uses: actions/download-artifact@v3
      with:
        name: ios
    - uses: actions/download-artifact@v3
      with:
        name: web
    - uses: actions/download-artifact@v3
      with:
        name: linux
    - uses: actions/download-artifact@v3
      with:
        name: windows
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          app-release.apk
          app-release.aab
          Runner.app
          web/*
          linux/*
          windows/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
